KutuphaneOtomasyonu/KutuphaneOtomasyonu/Areas/Ogrenci/Controllers/KitaplikController.cs
using AutoMapper;
using KutuphaneOtomasyonu.Entity.Dtos.Kitaps;
using KutuphaneOtomasyonu.Entity.Dtos.OkunanKitaplars;
using KutuphaneOtomasyonu.Service.Services.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;

namespace KutuphaneOtomasyonu.Web.Areas.Ogrenci.Controllers
{
    [Area("Ogrenci")]
    [Authorize(Roles = "Ogrenci")]
    public class KitaplikController : Controller
    {
        private readonly IKitapService kitapService;
        private readonly IKitaplikService kitaplikService;
        private readonly IOkunanKitaplarService okunanKitaplarService;
        private IMapper mapper;
        public KitaplikController(IKitaplikService kitaplikservice, IMapper mapper, IKitapService kitapService, IOkunanKitaplarService okunanKitaplarService)
        {
            this.kitaplikService = kitaplikservice;
            this.kitapService = kitapService;
            this.okunanKitaplarService = okunanKitaplarService;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            var kitaplik = await kitaplikService.GetAllKitaplikAsync();
            return View(kitaplik.ToPagedList(page, 5));
        }
        public async Task<IActionResult> KitaplikDetay(int id, int page = 1)
        {
            var kitap = await kitapService.GetKitapByKitaplikAsync(id);
            var kitapDto = mapper.Map<List<KitapDto>>(kitap);
            return View(kitapDto.ToPagedList(page, 5));
        }
        public async Task<IActionResult> KitapGorus(int id, int page = 1)
        {
            var okunanKitaplar = await okunanKitaplarService.GetOkunanKitaplarByKitapAsync(id);
            var okunanKitaplarDto = mapper.Map<List<OkunanKitaplarDto>>(okunanKitaplar);
            return View(okunanKitaplarDto.ToPagedList(page, 5));
        }
    }
}

KutuphaneOtomasyonu/KutuphaneOtomasyonu/ViewComponents/_LayoutViewComponents/_LayoutViewComponent.cs
using KutuphaneOtomasyonu.Service.Services.Abstractions;
using KutuphaneOtomasyonu.Service.Services.Concretes;
using Microsoft.AspNetCore.Mvc;

namespace KutuphaneOtomasyonu.Web.ViewComponents._LayoutViewComponents
{
    public class _LayoutViewComponent : ViewComponent
    {
        private readonly IAppUserService appUserService;

        public _LayoutViewComponent(IAppUserService appUserService)
        {
            this.appUserService = appUserService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var appUsers = await appUserService.GetAllAppUserAsync();
            return View(appUsers);
        }
    }
}

KutuphaneOtomasyonu/KutuphaneOtomasyonu/Areas/Ogretmen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/startbootstrap-sb-admin-2-gh-pages/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/startbootstrap-sb-admin-2-gh-pages/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a href="@Url.Action("Index", "Ogretmen", new { area = "Ogretmen" })" class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-book"></i>
                </div>
                <div class="sidebar-brand-text mx-3">KÜTÜPHANE</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
         <li class="nav-item active">
                <a asp-controller="Kitaplik" asp-action="Index" asp-area="Ogretmen" class="nav-link">
                    <i class="fas fa-solid fa-book"></i>
                    <span>Kitaplık</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">

            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-"></i>
                    <span>Öğrenci Kontrolü</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    @await Component.InvokeAsync("_Layout")
                </div>
            </li>


        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">


                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Kullanıcı</span>
                                <img class="img-profile rounded-circle"
                                     src="~/startbootstrap-sb-admin-2-gh-pages/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">

                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Logout">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    ÇıkışYap
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- Begin Page Content -->
            @RenderBody()
        </div>
<!-- End of Content Wrapper -->
    </div>
<!-- End of Page Wrapper -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
        <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js"></script>
        <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
        <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
        <script src="~/startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
        <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/chart.js/Chart.min.js"></script>

<!-- Page level custom scripts -->
        <script src="~/startbootstrap-sb-admin-2-gh-pages/js/demo/chart-area-demo.js"></script>
        <script src="~/startbootstrap-sb-admin-2-gh-pages/js/demo/chart-pie-demo.js"></script>

</body>